modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"
[[mods]]
modId = "jeitweaker"
version = "${file.jarVersion}"
displayName = "JEI Tweaker"
authors = "Jaredlll08"
updateJSONURL = "https://updates.blamejared.com/get?n=JEITweaker&gv=1.18.1"
description = '''
Adds JEI integration for CraftTweaker
'''
  [[dependencies.jeitweaker]]
	modId = "forge"
	mandatory = true
	versionRange = "[39,)"
	ordering = "NONE"
	side = "BOTH"
  [[dependencies.jeitweaker]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.18.1,)"
	ordering = "NONE"
	side = "BOTH"
  [[dependencies.jeitweaker]]
	modId = "crafttweaker"
	mandatory = true
	versionRange = "[9.0.0+15,)"
	ordering = "NONE"
	side = "BOTH"
  [[dependencies.jeitweaker]]
	modId = "jei"
	mandatory = false
	versionRange = "[9.2.1.69,)"
	ordering = "NONE"
	side = "BOTH"
