modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT"
[[mods]]
modId = "jeitweaker"
version = "${file.jarVersion}"
displayName = "JEI Tweaker"
authors = "Jaredlll08"
updateJSONURL = "https://updates.blamejared.com/get?n=JEITweaker&gv=1.17.1"
description = '''
Adds JEI integration for CraftTweaker
'''
  [[dependencies.jeitweaker]]
	modId = "forge"
	mandatory = true
	versionRange = "[37,)"
	ordering = "NONE"
	side = "BOTH"
  [[dependencies.jeitweaker]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.17.1,)"
	ordering = "NONE"
	side = "BOTH"
  [[dependencies.jeitweaker]]
	modId = "crafttweaker"
	mandatory = true
	versionRange = "[8.0.0+22,)"
	ordering = "NONE"
	side = "BOTH"
  [[dependencies.jeitweaker]]
	modId = "jei"
	mandatory = false
	versionRange = "[8.1.0.26,)"
	ordering = "NONE"
	side = "BOTH"
